stages:
  - iOS
  - Simulator
  
    
Package iOS:
 stage: iOS
 script:
    - xcodebuild archive -workspace FyndXcframework.xcworkspace -scheme FyndXcframework -destination "generic/platform=iOS Simulator" -archivePath "archives/fyndFDK-iOS-Simulator" SKIP_INSTALL=NO BUILD_LIBRARY_FOR_DISTRIBUTION=YES
 tags:
    - ios,xcode
 only:
    - feature/create-framework
    
Package Simulator:
 stage: Simulator
 script:
    - xcodebuild archive -workspace FyndXcframework.xcworkspace -scheme FyndXcframework -destination "generic/platform=iOS" -archivePath "archives/fyndFDK-iOS-Simulator" SKIP_INSTALL=NO BUILD_LIBRARY_FOR_DISTRIBUTION=YES
 tags:
    - ios,xcode
 only:
    - feature/create-framework

#
#Create Alamofire:
# stage: create Alamofire
# script:
#    - xcodebuild -create-xcframework -framework /Users/rushangprajapati/Documents/FyndProject/fyndxcframework/archives/fyndFDK-iOS-Simulator.xcarchive/Products/Library/Frameworks/Alamofire.framework -debug-symbols /Users/rushangprajapati/Documents/FyndProject/fyndxcframework/archives/fyndFDK-iOS-Simulator.xcarchive/dSYMs -framework /Users/rushangprajapati/Documents/FyndProject/fyndxcframework/archives/fyndFDK-iOS.xcarchive/Products/Library/Frameworks/Alamofire.framework -debug-symbols /Users/rushangprajapati/Documents/FyndProject/fyndxcframework/archives/fyndFDK-iOS.xcarchive/dSYMs -output FDKFyndJSK.xcframework
# tags:
#    - ios,xcode
# only:
#    - feature/create-framework
#
#Create CryptoSwift:
# stage: create CryptoSwift
# script:
#    - xcodebuild -create-xcframework -framework /Users/rushangprajapati/Documents/FyndProject/fyndxcframework/archives/fyndFDK-iOS-Simulator.xcarchive/Products/Library/Frameworks/CryptoSwift.framework -debug-symbols /Users/rushangprajapati/Documents/FyndProject/fyndxcframework/archives/fyndFDK-iOS-Simulator.xcarchive/dSYMs -framework /Users/rushangprajapati/Documents/FyndProject/fyndxcframework/archives/fyndFDK-iOS.xcarchive/Products/Library/Frameworks/CryptoSwift.framework -debug-symbols /Users/rushangprajapati/Documents/FyndProject/fyndxcframework/archives/fyndFDK-iOS.xcarchive/dSYMs -output FDKFyndJSK.xcframework
# tags:
#    - ios,xcode
# only:
#    - feature/create-framework
#
#Create FDKClient:
# stage: create FDKClient
# script:
#    - xcodebuild -create-xcframework -framework /Users/rushangprajapati/Documents/FyndProject/fyndxcframework/archives/fyndFDK-iOS-Simulator.xcarchive/Products/Library/Frameworks/FDKClient.framework -debug-symbols /Users/rushangprajapati/Documents/FyndProject/fyndxcframework/archives/fyndFDK-iOS-Simulator.xcarchive/dSYMs -framework /Users/rushangprajapati/Documents/FyndProject/fyndxcframework/archives/fyndFDK-iOS.xcarchive/Products/Library/Frameworks/FDKClient.framework -debug-symbols /Users/rushangprajapati/Documents/FyndProject/fyndxcframework/archives/fyndFDK-iOS.xcarchive/dSYMs -output FDKFyndJSK.xcframework
# tags:
#    - ios,xcode
# only:
#    - feature/create-framework
