stages:
    - Archive iOS
    - Archive Simulator
    - create Alamofire
    - create CryptoSwift
    - create FDKClient
    
Package Archive:
 stage: Archive iOS
 script:
    - xcodebuild archive -workspace fyndFDK.xcworkspace -scheme fyndFDK -destination "generic/platform=iOS" -archivePath "archives/fyndFDK-iOS" SKIP_INSTALL=NO BUILD_LIBRARY_FOR_DISTRIBUTION=YES
    - bundle exec fastlane customLane
 tags:
    - git, ssh
 only:
    - feature/create-framework

Package Archive:
 stage: Archive Simulator
 script:
    - xcodebuild archive -workspace fyndFDK.xcworkspace -scheme fyndFDK -destination "generic/platform=iOS Simulator" -archivePath "archives/fyndFDK-iOS-Simulator" SKIP_INSTALL=NO BUILD_LIBRARY_FOR_DISTRIBUTION=YES
 tags:
    - git, ssh
 only:
    - feature/create-framework
    
Create Alamofire:
 stage: create Alamofire
 script:
    - xcodebuild -create-xcframework -framework /Users/rushangprajapati/Desktop/fyndFDK/archives/fyndFDK-iOS-Simulator.xcarchive/Products/Library/Frameworks/Alamofire.framework -debug-symbols /Users/rushangprajapati/Desktop/fyndFDK/archives/fyndFDK-iOS-Simulator.xcarchive/dSYMs -framework /Users/rushangprajapati/Desktop/fyndFDK/archives/fyndFDK-iOS.xcarchive/Products/Library/Frameworks/Alamofire.framework -debug-symbols /Users/rushangprajapati/Desktop/fyndFDK/archives/fyndFDK-iOS.xcarchive/dSYMs -output FDKFyndJSK.xcframework
 tags:
    - git, ssh
 only:
    - feature/create-framework

Create CryptoSwift:
 stage: create CryptoSwift
 script:
    - xcodebuild -create-xcframework -framework /Users/rushangprajapati/Desktop/fyndFDK/archives/fyndFDK-iOS-Simulator.xcarchive/Products/Library/Frameworks/CryptoSwift.framework -debug-symbols /Users/rushangprajapati/Desktop/fyndFDK/archives/fyndFDK-iOS-Simulator.xcarchive/dSYMs -framework /Users/rushangprajapati/Desktop/fyndFDK/archives/fyndFDK-iOS.xcarchive/Products/Library/Frameworks/CryptoSwift.framework -debug-symbols /Users/rushangprajapati/Desktop/fyndFDK/archives/fyndFDK-iOS.xcarchive/dSYMs -output FDKFyndJSK.xcframework
 tags:
    - git, ssh
 only:
    - feature/create-framework

Create FDKClient:
 stage: create FDKClient
 script:
    - xcodebuild -create-xcframework -framework /Users/rushangprajapati/Desktop/fyndFDK/archives/fyndFDK-iOS-Simulator.xcarchive/Products/Library/Frameworks/FDKClient.framework -debug-symbols /Users/rushangprajapati/Desktop/fyndFDK/archives/fyndFDK-iOS-Simulator.xcarchive/dSYMs -framework /Users/rushangprajapati/Desktop/fyndFDK/archives/fyndFDK-iOS.xcarchive/Products/Library/Frameworks/FDKClient.framework -debug-symbols /Users/rushangprajapati/Desktop/fyndFDK/archives/fyndFDK-iOS.xcarchive/dSYMs -output FDKFyndJSK.xcframework
 tags:
    - git, ssh
 only:
    - feature/create-framework
